fix: 401 unauthenticated error ``` 2025-07-29T21:57:37.930Z ERROR 1 --- [nio-8075-exec-5] o.t.c.dex.DexCredentialAuthentication    : Generate Dex Authentication Private Token 2025-07-29T21:57:37.933Z ERROR 1 --- [nio-8075-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: feign.RetryableException: Too many follow-up requests: 21 executing GET http://terrakube-api-service:8080/api/v1/organization?filter%5Borganization%5D=name==Omniscient] with root cause
java.net.ProtocolException: Too many follow-up requests: 21
```